#!/bin/bash


# comments
#echo "The current directory is:"

#pwd

#echo "The user logged in is:"

#whoami

#display user home

#echo "Home for the current user is: $HOME"


# testing variables
#grade=5
#person="Adam"
#echo "$person is a good boy, he is in grade $grade"

#mydir=$(pwd)
#echo $mydir
#var1=$(( 5 + 5 ))
#echo $var1
#var2=$(( $var1 * 2 ))
#echo $var2
#echo "$1"
#echo "$2"
#echo "$0"

if pwd
then
echo "It works"
fi

user=basic_45-46e

if grep $user /etc/passwd
then
echo "The user $user Exists"
fi


user=anotherUser
if grep $user /etc/passwd
then
echo "The user $user Exists"
else
echo "The user $user doesn’t exist"
fi


